set background=dark
" Set 'nocompatible' to ward off unexpected things that your distro might
" have made, as well as sanely reset options when re-sourcing .vimrc
set nocompatible

" Attempt to determine the type of a file based on its name and possibly its
" contents. Use this to allow intelligent auto-indenting for each filetype,
" and for plugins that are filetype specific.
if has('filetype')
  filetype indent plugin on
endif

"Turn on syntax highlighting
syntax on
"------------------------------------------------------------
" Must have options {{{1
"
" These are highly recommended options.

" Vim with default settings does not allow easy switching between multiple files
" in the same editor window. Users can use multiple split windows or multiple
" tab pages to edit multiple files, but it is still best to enable an option to
" allow easier switching between files.
"
" One such option is the 'hidden' option, which allows you to re-use the same
" window and switch from an unsaved buffer without saving it first. Also allows
" you to keep an undo history for multiple files when re-using the same window
" in this way. Note that using persistent undo also lets you undo in multiple
" files even in the same window, but is less efficient and is actually designed
" for keeping undo history after closing Vim entirely. Vim will complain if you
" try to quit without saving, and swap files will keep you safe if your computer
" crashes.
"set hidden

" Note that not everyone likes working this way (with the hidden option).
" Alternatives include using tabs or split windows instead of re-using the same
" window as mentioned above, and/or either of the following options:
" set confirm
" set autowriteall

" Better command-line completion
set wildmenu

" Show partial commands in the last line of the screen
set showcmd

" Highlight searches (use <C-L> to temporarily turn off highlighting; see the
" mapping of <C-L> below)
set hlsearch

" Modelines have historically been a source of security vulnerabilities. As
" such, it may be a good idea to disable them and use the securemodelines
" script, <http://www.vim.org/scripts/script.php?script_id=1876>.
" set nomodeline


"------------------------------------------------------------
" Usability options {{{1
"
" These are options that users frequently set in their .vimrc. Some of them
" change Vim's behaviour in ways which deviate from the true Vi way, but
" which are considered to add usability. Which, if any, of these options to
" use is very much a personal preference, but they are harmless.

" Use case insensitive search, except when using capital letters
set ignorecase
set smartcase

" Allow backspacing over autoindent, line breaks and start of insert action
set backspace=indent,eol,start

" When opening a new line and no filetype-specific indenting is enabled, keep
" the same indent as the line you're currently on. Useful for READMEs, etc.
set autoindent

" Stop certain movements from always going to the first character of a line.
" While this behaviour deviates from that of Vi, it does what most users
" coming from other editors would expect.
set nostartofline

" Display the cursor position on the last line of the screen or in the status
" line of a window
set ruler

" Always display the status line, even if only one window is displayed
set laststatus=2
      
" Instead of failing a command because of unsaved changes, instead raise a
" dialogue asking if you wish to save changed files.
set confirm

" Use visual bell instead of beeping when doing something wrong
set visualbell

" And reset the terminal code for the visual bell. If visualbell is set, and
" this line is also included, vim will neither flash nor beep. If visualbell
" is unset, this does nothing.
set t_vb=

" Enable use of the mouse for all modes
if has('mouse')
  set mouse=nv
endif

" Set the command window height to 2 lines, to avoid many cases of having to
" "press <Enter> to continue"
set cmdheight=2

" Display line numbers on the left
"set number
set relativenumber
" Quickly time out on keycodes, but never time out on mappings
set notimeout ttimeout ttimeoutlen=200

" Use <F11> to toggle between 'paste' and 'nopaste'
set pastetoggle=<F11>

"------------------------------------------------------------
" color change
colorscheme elflord
highlight Comment ctermfg=green cterm=none
highlight Type ctermfg=Cyan cterm=bold
highlight Keyword ctermfg=Cyan cterm=bold
highlight String ctermfg=red cterm=bold
highlight LineNr ctermfg=yellow cterm=bold


"------------------------------------------------------------
"
" Indentation settings according to personal preference.
" shiftwidth for typing >>
set shiftwidth=4
" tabstop for typing tab
set tabstop=4

set softtabstop=4
set expandtab

set pastetoggle=<F2>
" Map <C-"L> (redraw screen) to also turn off search highlighting until the
" next search
nnoremap <C-L> :nohl<CR><C-L>

"------------------------------------------------------------
" Use a line cursor within insert mode and a block cursor everywhere else.
"
" Reference chart of values:
"   Ps = 0  -> blinking block.
"   Ps = 1  -> blinking block (default).
"   Ps = 2  -> steady block.
"   Ps = 3  -> blinking underline.
"   Ps = 4  -> steady underline.
"   Ps = 5  -> blinking bar (xterm).
"   Ps = 6  -> steady bar (xterm).
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"
"------------------------------------------------------------
" Highlight cursor line underneath the cursor horizontally.
"set cursorline

" Highlight cursor line underneath the cursor vertically.
" Black   : 0
" Red     : 1
" Green   : 2
" Yellow  : 3
" Blue    : 4
" Magenta : 5
" Cyan    : 6
" White   : 7
set cursorcolumn

"highlight CursorLine   cterm=NONE ctermbg=7
highlight CursorColumn cterm=NONE ctermbg=4 ctermfg=7

highlight Visual cterm=NONE ctermbg=7 ctermfg=0

"------------------------------------------------------------
" system verilog
"Enable matchit
runtime macros/matchit.vim
if v:version < 800
    "Start pathogen
    execute pathogen#infect()
endif
"Enable filetype detection
filetype plugin indent on
"Enable folding based on indent (on 8.0 and greater versions)
if v:version >= 800
    set foldmethod=indent
    set foldnestmax=10
    set nofoldenable
    set foldlevelstart=10
endif
"------------------------------------------------------------
" copy
nnoremap Y "+y
vnoremap Y "+y
vnoremap y y`]
"------------------------------------------------------------
" comment by type \/
" uncomment by type \?
" <leader> is \
augroup my_comment
    autocmd!
    " verilog code
    autocmd FileType systemverilog,verilog,c vnoremap <buffer> <leader>/ :s/^/\/\/ /<CR>:noh<CR>
    autocmd FileType systemverilog,verilog,c vnoremap <buffer> <leader>? :s/^\/\/ //<CR>:noh<CR>
    " shell
    autocmd FileType csh,sh,tcsh vnoremap <buffer> <leader>/ :s/^/# /<CR>:noh<CR>
    autocmd FileType csh,sh,tcsh vnoremap <buffer> <leader>? :s/^# //<CR>:noh<CR>
    " vim
    autocmd FileType vim vnoremap <buffer> <leader>/ :s/^/" /<CR>:noh<CR>
    autocmd FileType vim vnoremap <buffer> <leader>? :s/^" //<CR>:noh<CR>
augroup END

"------------------------------------------------------------
" Enter Visual mode → turn OFF cursor helpers
"nnoremap <silent> v     :set nocursorcolumn nocursorline<CR>v
"nnoremap <silent> V     :set nocursorcolumn nocursorline<CR>V
"nnoremap <silent> <C-v> :set nocursorcolumn nocursorline<CR><C-v>
"
"" Leave Visual mode → restore cursor helpers
"vnoremap <silent> <Esc> <Esc>:set cursorcolumn cursorline<CR>
